application: jagare
version: 1
runtime: python
api_version: 1
# irc_report_channel: code
report_observer_emails: lihan@intern.douban.com

release_managers:
- xutao
- lh_intern
- lihan

# services:
# - interface:
#

# services_idls:
# - jagare.thrift

handlers:
- url: /.*
  wsgi_app: app:app

selftest:
- url: /
  status: 200
